### ISSUE TITLE
Are cycles allowed in function chaining?

### ISSUE THREAD

**Issue by csegarragonz** [faasm/faabric#34]
Is the following scenario sane?
* `f_0` (main driver) calls `f_1`
* `f_1` performs a step in a iterative operation, and checks against a convergence value.
* Depending on the outcome, either calls itself or returns.

This is the simplest cycle I could think of (a loop), but it's easy to imagine a cycle of length 3. My question is whether this is something that could happen.

If so, my concern is that the current recursion in `Scheduler::getFunctionExecGraphNode` would not handle it correctly. I can't find any place where this is actually called, but worth noting.

**Comment by Shillaker** [comment]
You need to be more precise in your question as it's too ambiguous to answer. There can be many _instances_ of a given function, so you need to state whether you're talking about functions (which are like a class, of which many instances can exist), or instances of functions (which are unique). You also need to be more precise on what you mean by "calling" a function, do you mean a single instance of a function making a chained call to the same function (and thereby causing a _new_ instance to be created), or something else? I'm not sure what this other mechanism would be.

I think Github Issues are a very inefficient way to discuss things like this; it takes much longer to type out an answer than to say it on a call, so we should discuss things like this in person in future. If a useful piece of information comes out of such a discussion, we can write it in the docs so that it's available.

**Comment by Shillaker** [comment]
Also note that the current execution graph is for _retrospective_ analysis of where functions were executed, and is not used in scheduling at all.
